version: '3.5'

services:
  postgres:
    container_name: test
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "test:test"
    restart: unless-stopped
volumes:
  postgres: