env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8083"
  timeout: 4s
  idle_timeout: 60s
postgres_config:
  host: "localhost"
  port: "5432"
  username: "root"
  password: "1234"
  database: "postgres"